=== marioarnedo98/1-Curso-DAW/Sistema de Lenguajes de Marcas/XML/tema 5 cd Lenguaje/cd_p1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="cdteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="cd"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="cd">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="titulo"/>
        <xs:element ref="artista"/>
        <xs:element maxOccurs="unbounded" ref="cancion"/>
        <xs:element ref="sello"/>
        <xs:element ref="anyo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titulo" type="xs:string"/>
  <xs:element name="artista" type="xs:string"/>
  <xs:element name="cancion">
    <xs:complexType mixed="true">
      <xs:attribute name="tiempo" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sello" type="xs:NCName"/>
  <xs:element name="anyo" type="xs:integer"/>
</xs:schema>

=== marioarnedo98/1-Curso-DAW/Sistema de Lenguajes de Marcas/XML/tema 5 cd Lenguaje/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<cdteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/daw2/Desktop/tema%205%20cd%20Lenguaje/cd_p1.xsd">
    <cd>
        <titulo>titulo0</titulo>
        <artista>artista0</artista>
        <cancion tiempo="0">
        </cancion>
        <cancion tiempo="0">
        </cancion>
        <sello>sello0</sello>
        <anyo>0</anyo>
    </cd>
    <cd>
        <titulo>titulo1</titulo>
        <artista>artista1</artista>
        <cancion tiempo="0">
        </cancion>
        <cancion tiempo="0">
        </cancion>
        <sello>sello1</sello>
        <anyo>0</anyo>
    </cd>
</cdteca>
