=== marioarnedo98/1-Curso-DAW/Sistema de Lenguajes de Marcas/XML/prueba.dtd
<!ELEMENT persona (nombre, nacimiento, direccion, (varon|mujer))>
<!ELEMENT nombre (#PCDATA)>
<!DATALIST [nacimiento
dia CDATA #REQUIRED 
mes CDATA #REQUIRED
anyo CDATA #REQUIRED
]>
<!ELEMENT direccion (calle, poblacion, provincia, cpostal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ELEMENT varon EMPTY>
<!ELEMENT mujer EMPTY>

=== marioarnedo98/1-Curso-DAW/Sistema de Lenguajes de Marcas/XML/persona.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Libros SYSTEM "prueba.dtd">
<persona>
<nombre>Juan</nombre>
<nacimiento dia="10" mes="Abril" anyo="1465"/>
<direccion>
<calle>Pepe,2</calle>
<poblacion>Logroño</poblacion>
<provincia>La Rioja</provincia>
<cpostal>24142</cpostal>
</direccion>
<varon/>
</persona>
<persona>
<nombre>Mario</nombre>
<nacimiento dia="3" mes="Diciembre" anyo="1998"/>
<direccion>
<calle>Juan,343</calle>
<poblacion>Logroño</poblacion>
<provincia>La Rioja</provincia>
<cpostal>22142</cpostal>
</direccion>
<varon/>
</persona>
